#!/usr/bin/env python
# encoding:utf-8
#
# Download videos from the Dutch `Uitzending gemist' site.
#
# http://code.arp242.net/download-gemist
#
# Copyright © 2012-2013 Martin Tournoij <martin@arp242.net>
# See below for full copyright
#

from __future__ import print_function
import getopt
import sys

import dgemist

_verbose = False


def Help():
	print('%s [-phvV] [url]' % sys.argv[0])
	print ('')
	print("  -p    Aantal pagina\'s, standaard 1")
	print('  -h    Toon deze help')
	print('  -v    Toon versie')
	print('  -V    Print meer informatie naar het scherm')


def Version():
	print('download-gemist ' + dgemist.GetVersion())
	print('http://code.arp242.net/download-gemist')


def Error(msg):
	""" Print message to stderr, can't use print because of Python 2/3
	incompatibility """
	sys.stderr.write('Error: %s\n' % msg)


if __name__ == '__main__':
	try:
		options, program = getopt.getopt(sys.argv[1:], 'hvVp:')
	except getopt.GetoptError as e:
		Error(e.message)
		Help()
		sys.exit(1)

	pages = 0
	for flag, arg in options:
		if flag == '-h':
			Help()
			sys.exit(0)
		elif flag == '-v':
			Version()
			sys.exit(0)
		elif flag == '-V':
			_verbose = True
			dgemist._verbose = True
		elif flag == '-p':
			pages = int(arg)

	if len(program) == 0:
		sys.stderr.write('Lezen van stdin (gebruik -h voor help)...')
		sys.stderr.flush()
		program = sys.stdin.read().strip().split(' ')

	for v in dgemist.GetListing(program[0], pages):
		print('|'.join(v))


# The MIT License (MIT)
#
# Copyright © 2012-2013 Martin Tournoij
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# The software is provided "as is", without warranty of any kind, express or
# implied, including but not limited to the warranties of merchantability,
# fitness for a particular purpose and noninfringement. In no event shall the
# authors or copyright holders be liable for any claim, damages or other
# liability, whether in an action of contract, tort or otherwise, arising
# from, out of or in connection with the software or the use or other dealings
# in the software.
