#!/usr/bin/env python
#
# Download videos from the Dutch `Uitzending gemist' site.
#
# http://code.arp242.net/download-gemist/
#
# Copyright (c) 2012 Martin Tournoij <martin@arp242.net>
# See below for full copyright
#

from __future__ import print_function

import getopt
import re
import sys

# Python 2
try:
	import urllib2
	from HTMLParser import HTMLParser
# Python 3
except ImportError:
	import urllib.request as urllib2
	from html.parser import HTMLParser

_verbose = False
_silent = False

def Help():
	print('%s [-hvV] [url]' % sys.argv[0])
	print ('')
	print('  -h    Show this help')
	print('  -v    Show version')
	print('  -V    Show verbose information')

def Version():
	print('download-gemist 1.3, 2013-01-22')
	print('http://code.arp242.net/download-gemist/')
	print('')
	print('Copyright (c) Martin Tournoij <martin@arp242.net>')
	print('Freely redistributable and modifiable under the terms of the MIT license')
	print('http://opensource.org/licenses/MIT')

def Error(msg):
	"""
	Print message to stderr, can't use print because of Python 2/3
	incompatibility
	"""

	sys.stderr.write(msg + '\n')

def OpenUrl(url):
	"""
	Build request, fake headers & mandatory cookie
	"""
	headers = {
		'User-Agent': 'Opera/9.80 (X11; FreeBSD 9.0-RELEASE amd64; U; en) Presto/2.10.289 Version/12.02',
		'Cookie': 'site_cookie_consent=yes',
	}
	req = urllib2.Request(url, headers=headers)
	page = urllib2.urlopen(req)

	if _verbose:
		print('OpenUrl url: ' + url)

	return (page.info(), page.read())

def ProcProgram(url, pages):
	videos = []
	for page in range(1, pages + 1):
		head, data = OpenUrl('%s/afleveringen?page=%s' % (url, page))

		for g in ProcPage(data):
			epid, title, desc = g
			title = HTMLParser().unescape(re.sub('\(.*?\)', '', title)).strip()
			desc = HTMLParser().unescape(desc).strip()

			videos.append([
				epid,
				title,
				'http://www.uitzendinggemist.nl/afleveringen/%s' % (epid),
				desc,
			])

	return videos

def ProcPage(data):
	#<a href="/afleveringen/1287960" class="episode active knav_link" title="Kabinet in crisis  (zo 9 sep 2012, 21:20)">Kabinet in crisis <img alt="888" class="tt888" src="//assets.www.uitzendinggemist.nl/assets/tt888.png" title="Deze aflevering is TT888 ondertiteld" /> <span class="date">(zo 9 sep 2012, 21:20)</span></a></h3>

	return re.findall('<li class="episode active knav".*?data-remote-id="\d+?" id="episode_(\d+)">.*?<a href="/afleveringen/\d+?" class="episode active knav_link" title="(.+?)">.+?</h3>(.+?)</div>', data, re.MULTILINE | re.DOTALL)

if __name__ == '__main__':
	try:
		options, program = getopt.getopt(sys.argv[1:], 'hvVsno:p:')
	except getopt.GetoptError:
		Error('Error:', sys.exc_info()[1])
		Help()
		sys.exit(1)

	pages = 1
	outdir = '.'
	for flag, arg in options:
		if flag == '-h':
			Help()
			sys.exit(0)
		elif flag == '-v':
			Version()
			sys.exit(0)
		elif flag == '-V':
			_verbose = True
		elif flag == '-s':
			_silent = True
		elif flag == '-o':
			outdir = arg
		elif flag == '-p':
			pages = int(arg)

	if len(program) == 0:
		print('URL required')
		Help()
		sys.exit(1)

	videos = ProcProgram(program[0], pages)

	for v in videos:
		print('|'.join(v))


# The MIT License (MIT)
#
# Copyright (c) 2012 Martin Tournoij
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.
