#!/bin/sh
#

echo "Python 2 doctests"
#python2 dgemist/__init__.py
echo

echo "Python 3 doctests"
#python3 dgemist/__init__.py
echo


echo -n "Testing download-gemist-list "
listpages="\
programmas/215-andere-tijden
programmas/2617-de-rekenkamer
weekarchief/gisteren"
IFS="
"
for p in $listpages; do
	p=http://www.uitzendinggemist.nl/$p
	if [ $(python2 download-gemist-list $p | wc -l | tr -d ' ') -lt 3 ]; then
		echo "*** Error -> python2 download-gemist-list $p ***"
	else
		echo -n "."
	fi

	if [ $(python3 download-gemist-list $p | wc -l | tr -d ' ') -lt 3 ]; then
		echo "*** Error -> python3 download-gemist-list $p ***"
	else
		echo -n "."
	fi
done
echo ""


echo -n "Testing download-gemist "
videopages="\
http://www.uitzendinggemist.nl/afleveringen/1346967
http://deslimstemens.ncrv.nl/ncrvgemist/27-12-2013/slimste-mens
http://www.npo.nl/vredesmacht-onder-vuur/22-12-2013/NPS_1218718"
IFS=" "
for p in $videopages; do
	if [ "$(python2 download-gemist -n $p)" != "Okay!" ]; then
		echo "*** Error -> python2 download-gemist -n $p ***"
	else
		echo -n "."
	fi

	if [ "$(python3 download-gemist -n $p)" != "Okay!" ]; then
		echo " ***Error -> python3 download-gemist -n $p ***"
	else
		echo -n "."
	fi
done
echo ""
